version: '3'
services:
  web:
    build:
      dockerfile: ./jogo/docker/flask.dockerfile
      context: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - ./jogo:/jogo